@startuml

!theme materia

skinparam Padding 2
skinparam linetype ortho

entity "Firm" as ent {
    name<PK>: string
    parent<FK>: string
    catCode<FK>: string
    catSource: string
}

entity "Industry" as indust {
    Catcode<PK>: string
    --
    Catname: string
    Catorder: string
    Industry: string
    Sector: string
    SectorLong: string
}

entity "LobbyingFirm" as lobf {
    Name<FK>: string
}

entity "Agency" as agency {
    Uniqid<FK>: string
    Name: string
}

entity "LobbyingRecord" as lr {
    Uniqid<FK>: string
    Registrant<FK>: string
    Client<FK>: string
    Isfirm: boolean
    Amount: float
    Source: string
    Self: char
    Type: string
    Affiliate: bool
}

entity "Lobbyist" as lob {
    Name: string
    Uniqid<FK>: string
}

entity "Bill" as bill {
    BillID<PK>: int
    SI_ID<FK>: string
    CongNo: int
    BillName: string
}

entity "Specific Issue" as si {
    SI_ID<PK>: string
    UniqID<FK>: string
    SpecificIssue: string
    IssueID<FK>: string
}

entity "Issue" as issue {
    IssueID<PK>: string
    Issue: string
}

ent}|..||ent:SUBSIDIARY_OF
ent||..|{indust:BELONGS_TO
ent||..|{lr:LOBBIES
lobf||..o{lr:LOBBIES_THROUGH
lob}|..|{lr:WORKED_ON
lob}|..|{lobf:WORKS_FOR
lr}|..||agency:LOBBIED
bill||..|{lr:LOBBIED_ON
bill||..|{si:RELATED_TO
lr}|..||si:CONCERNS
si}|..||issue:MAIN_ISSUE

@enduml